In [33]:
%load_ext autoreload
%autoreload 2

import os
import pandas as pd
import matplotlib.pyplot as plt
from plot_utils import plot_search_curves, plot_best_fitness, plot_gap_scatter, plot_gap_scatter_from_sol
%matplotlib notebook

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [34]:
from plot_utils import plot_best_fitness

algorithm_names = [
    'BKS',
    'AILSII_continue_1',
    # 'AILSII_continue_2',
    
    # 'AILSII_continue_eoh_1',
    # 'AILSII_continue_eoh_2'
    'EoH_Acc',
    'EoH_Omega'
    
]

instance_dir = '../XLTEST'
instance_names = [i.split('.')[0] for i in os.listdir(instance_dir)]
instance_names = [instance_names[i] for i in [70, 80, 90, 97]]

In [35]:
for instance in instance_names:
    plot_best_fitness(instance, algorithm_names, base_dir='../remote_results/test-bks', output_dir='../figures/bks_results')

--- 开始绘制【最佳Fitness】曲线: XLTEST-n9571-k980 ---
信息: 文件 None 未找到, 跳过。
AILSII_continue_1: 909 entries | best fitness: 1359894.0
EoH_Acc: 617 entries | best fitness: 1360047.0
EoH_Omega: 401 entries | best fitness: 1360850.0
--- 绘图完成: XLTEST-n9571-k980, 图像已保存至 ../figures/bks_results/plot_best_fitness_XLTEST-n9571-k980.png ---

--- 开始绘制【最佳Fitness】曲线: XLTEST-n3640-k144 ---
信息: 文件 None 未找到, 跳过。
AILSII_continue_1: 25 entries | best fitness: 138232.0
EoH_Acc: 24 entries | best fitness: 138228.0
警告: 文件 ../remote_results/test-bks/EoH_Omega/XLTEST-n3640-k144_1.csv 为空, 跳过。
--- 绘图完成: XLTEST-n3640-k144, 图像已保存至 ../figures/bks_results/plot_best_fitness_XLTEST-n3640-k144.png ---

--- 开始绘制【最佳Fitness】曲线: XLTEST-n3241-k628 ---
信息: 文件 None 未找到, 跳过。
警告: 文件 ../remote_results/test-bks/AILSII_continue_1/XLTEST-n3241-k628_2.csv 为空, 跳过。
EoH_Acc: 88 entries | best fitness: 468793.0
警告: 文件 ../remote_results/test-bks/EoH_Omega/XLTEST-n3241-k628_1.csv 为空, 跳过。
--- 绘图完成: XLTEST-n3241-k628, 图像已保存至 ../figures/bks_results/plot_best_fitness_XLTEST-n3241-k628.png ---

--- 开始绘制【最佳Fitness】曲线: XLTEST-n7037-k2302 ---
信息: 文件 None 未找到, 跳过。
AILSII_continue_1: 607 entries | best fitness: 3427706.0
警告: 文件 ../remote_results/test-bks/EoH_Acc/XLTEST-n7037-k2302_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-bks/EoH_Omega/XLTEST-n7037-k2302_1.csv 为空, 跳过。
--- 绘图完成: XLTEST-n7037-k2302, 图像已保存至 ../figures/bks_results/plot_best_fitness_XLTEST-n7037-k2302.png ---

In [36]:
instance_dir = '../XLTEST'
instance_names = [i.split('.')[0] for i in os.listdir(instance_dir)]
plot_gap_scatter_from_sol(instance_names, algorithm_names, base_dir='../remote_results/test-bks', output_dir='../figures/bks_results', point_alpha=0.5, point_size=20)

--- 开始绘制 Gap 分析 (基于 .sol 文件) ---
警告: 无法从实例名 genXLTEST 中提取客户数量，跳过此实例。
警告: 无法从实例名 generate_distri_csv 中提取客户数量，跳过此实例。
警告: 无法从实例名 generatorLarge 中提取客户数量，跳过此实例。

--- Gap 分析完成. 图像已保存至 ../figures/bks_results/gap_analysis_scatter_sol.png ---

In [37]:
from plot_utils import get_average_gap_statistics

df_avg_gap = get_average_gap_statistics(instance_names, algorithm_names, base_dir='../remote_results/test-bks', baseline='BKS')
df_avg_gap

--- 开始计算平均 Gap (基于 .sol 文件) | Baseline模式: BKS ---

--- 平均 Gap 统计表 ---
              Method  Average Gap (%)
1                BKS         0.000000
2            EoH_Acc         0.017287
0  AILSII_continue_1         0.018435
3          EoH_Omega         0.035766

              Method  Average Gap (%)
1                BKS         0.000000
2            EoH_Acc         0.017287
0  AILSII_continue_1         0.018435
3          EoH_Omega         0.035766

In [38]:
from plot_utils import get_rank_statistics

get_rank_statistics(instance_names, algorithm_names, base_dir='../remote_results/test-bks', output_csv='../figures/bks_results/rank_statistics.csv')

--- 开始统计算法排名情况 (区分 Strict/Tied Rank 1) ---

--- 排名统计表 (Rank Statistics) ---
Rank_Label         Strict Rank 1  Tied Rank 1  Rank 2  Rank 3  Rank 4
Method
AILSII_continue_1             31            3      32      26       8
BKS                           49            5      26      18       2
EoH_Acc                       13            2      46      34       4
EoH_Omega                      2            4      17      31      46
表格已保存至: ../figures/bks_results/rank_statistics.csv

Rank_Label         Strict Rank 1  Tied Rank 1  Rank 2  Rank 3  Rank 4
Method
AILSII_continue_1             31            3      32      26       8
BKS                           49            5      26      18       2
EoH_Acc                       13            2      46      34       4
EoH_Omega                      2            4      17      31      46

In [39]:
import os
import glob
import pandas as pd
from collections import deque

def get_max_time_from_csv(file_path):
    """
    读取CSV文件的最后一行以提取最大时间。
    如果文件为空，返回 0。
    """
    # 1. 检查文件是否为空
    if os.path.getsize(file_path) == 0:
        return 0.0

    try:
        # 2. 打开文件并只读取最后一行 (使用 deque 只保留最后1行)
        with open(file_path, 'r', encoding='utf-8') as f:
            # deque(f, 1) 会高效地只抓取最后一行
            last_line_gen = deque(f, maxlen=1)
            
            if not last_line_gen: # 双重检查：如果文件有大小但内容为空（如只有换行符）
                return 0.0
            
            last_line = last_line_gen[0].strip()
            
            # 3. 解析数据: {time};{fitness}
            # 假设格式总是分号分隔，且第一列是时间
            if not last_line:
                return 0.0
                
            time_str = last_line.split(';')[0]
            return float(time_str)
            
    except Exception as e:
        print(f"处理文件 {os.path.basename(file_path)} 时出错: {e}")
        return 0.0 # 出错时默认返回0，或者根据需求改为 None

In [40]:


# ================= 配置路径 =================
# ===========================================

def analysis_max_times(target_path):
    method_name = os.path.basename(target_path)
    
    # 获取所有csv文件
    csv_files = glob.glob(os.path.join(target_path, "*.csv"))
    data_list = []
    
    print(f"正在处理 {len(csv_files)} 个文件...")
    
    for file in csv_files:
        max_time = get_max_time_from_csv(file)
        # 记录文件名（不含路径）和最大时间
        data_list.append({
            'filename': os.path.basename(file),
            'max_time': max_time
        })
    
    # 1. 生成 DataFrame
    df = pd.DataFrame(data_list)
    
    # 按文件名排序（可选，方便查看）
    df = df.sort_values(by='filename').reset_index(drop=True)
    
    print("--- 结果预览 (前5行) ---")
    print(df.head())
    
    print(f"\n--- 统计信息 - {method_name} ---")
    # 2. 做个统计 (均值、最大值、最小值、分位数等)
    stats = df['max_time'].describe()
    print(stats)
    
    zero_count = (df['max_time'] == 0).sum()
    print(f"\n完全无提升instance个数: {zero_count} / {len(df)}")

# 如果你想查看具体的时间分布情况
# print(df['max_time'].value_counts(bins=10))

In [41]:
target_path = '../remote_results/test-bks/EoH_Acc'  # 请修改为你的实际文件夹路径
analysis_max_times(target_path)

正在处理 146 个文件...
--- 结果预览 (前5行) ---
                   filename    max_time
0  XLTEST-n10001-k806_1.csv      0.0000
1   XLTEST-n1048-k139_1.csv      0.0000
2   XLTEST-n1048-k139_2.csv  18307.1966
3     XLTEST-n1094-k9_1.csv      0.0000
4     XLTEST-n1094-k9_2.csv   3982.7663

--- 统计信息 - EoH_Acc ---
count       146.000000
mean      88187.567718
std       93115.266436
min           0.000000
25%           0.000000
50%       48143.195400
75%      188410.328825
max      234199.981600
Name: max_time, dtype: float64

完全无提升instance个数: 48 / 146

In [42]:
target_path = '../remote_results/test-bks/EoH_Omega'  # 请修改为你的实际文件夹路径
analysis_max_times(target_path)

正在处理 100 个文件...
--- 结果预览 (前5行) ---
                   filename     max_time
0  XLTEST-n10001-k806_1.csv  230412.0971
1   XLTEST-n1048-k139_1.csv       0.0000
2     XLTEST-n1094-k9_1.csv       8.2143
3    XLTEST-n1141-k75_1.csv       0.0000
4    XLTEST-n1188-k72_1.csv       0.0000

--- 统计信息 - EoH_Omega ---
count       100.000000
mean      66798.762658
std       99360.209251
min           0.000000
25%           0.000000
50%           0.000000
75%      196721.291050
max      233092.351700
Name: max_time, dtype: float64

完全无提升instance个数: 59 / 100

In [43]:
target_path = '../remote_results/test-bks/AILSII_continue_1'  # 请修改为你的实际文件夹路径
analysis_max_times(target_path)

正在处理 150 个文件...
--- 结果预览 (前5行) ---
                   filename  max_time
0  XLTEST-n10001-k806_1.csv   10.7988
1  XLTEST-n10001-k806_2.csv    0.0000
2   XLTEST-n1048-k139_1.csv    7.2966
3   XLTEST-n1048-k139_2.csv    0.0000
4     XLTEST-n1094-k9_1.csv    0.0000

--- 统计信息 - AILSII_continue_1 ---
count       150.000000
mean      99819.618206
std      143752.662791
min           0.000000
25%           0.000000
50%          10.708650
75%      283218.076325
max      345430.838800
Name: max_time, dtype: float64

完全无提升instance个数: 61 / 150