In [1]:
%load_ext autoreload
%autoreload 2

import os
import pandas as pd
import matplotlib.pyplot as plt
# from plot_utils import plot_search_curves, plot_best_fitness, plot_gap_scatter, plot_gap_scatter_from_sol, get_fitness_table
from plot_utils_v2 import load_results_dataframe, plot_gap_scatter, get_average_gap_statistics, get_rank_statistics
%matplotlib notebook

In [2]:
algorithm_names = [
    # 'AILSII_continue_1',
    # 'AILS2_EoH_Acc_large_continue.jar',
    'AILS2_EoH_Omega2_continue.jar',
    'BKS',
    # 'EoH_Acc',
    # 'EoH_Omega',
    # 'AILSII_continue_Mahdi',
    # 'Mahdi_baseline'
    # 'AILSII_continue_2',
    
    # 'AILSII_continue_eoh_1',
    # 'AILSII_continue_eoh_2'
    # 'EoH_Acc',
    # 'EoH_Omega'
    
]

# instance_dir = '../XLTEST'
instance_dir = '../XLTEST'

instance_names = [i.split('.')[0] for i in os.listdir(instance_dir) if i.endswith('.vrp')]
# instance_names = [instance_names[i] for i in [70, 80, 90, 97]]

In [3]:
import re
def extract_n_value(filename):
    # 正则表达式解释：
    # n      : 匹配字符 'n'
    # (\d+)  : 捕获组，匹配一个或多个数字
    match = re.search(r'n(\d+)', filename)
    if match:
        return int(match.group(1)) # 返回整数类型以便正确排序
    return 0 # 如果没找到，返回0排在最后

instance_names = sorted(instance_names, key=extract_n_value, reverse=False)

In [4]:
instance_names

['XLTEST-n1048-k139',
 'XLTEST-n1094-k9',
 'XLTEST-n1141-k75',
 'XLTEST-n1188-k72',
 'XLTEST-n1234-k252',
 'XLTEST-n1281-k42',
 'XLTEST-n1328-k115',
 'XLTEST-n1374-k71',
 'XLTEST-n1421-k12',
 'XLTEST-n1468-k47',
 'XLTEST-n1514-k125',
 'XLTEST-n1561-k156',
 'XLTEST-n1608-k488',
 'XLTEST-n1654-k322',
 'XLTEST-n1701-k10',
 'XLTEST-n1748-k293',
 'XLTEST-n1794-k405',
 'XLTEST-n1841-k37',
 'XLTEST-n1888-k206',
 'XLTEST-n1934-k107',
 'XLTEST-n1981-k146',
 'XLTEST-n2028-k406',
 'XLTEST-n2074-k225',
 'XLTEST-n2121-k107',
 'XLTEST-n2168-k625',
 'XLTEST-n2214-k61',
 'XLTEST-n2261-k168',
 'XLTEST-n2307-k13',
 'XLTEST-n2354-k217',
 'XLTEST-n2401-k16',
 'XLTEST-n2447-k199',
 'XLTEST-n2494-k624',
 'XLTEST-n2541-k92',
 'XLTEST-n2587-k114',
 'XLTEST-n2634-k380',
 'XLTEST-n2681-k15',
 'XLTEST-n2727-k175',
 'XLTEST-n2774-k349',
 'XLTEST-n2821-k336',
 'XLTEST-n2867-k169',
 'XLTEST-n2914-k852',
 'XLTEST-n2961-k73',
 'XLTEST-n3007-k152',
 'XLTEST-n3054-k306',
 'XLTEST-n3101-k685',
 'XLTEST-n3147-k215',
 'XLTEST-n3194-k93',
 'XLTEST-n3241-k628',
 'XLTEST-n3287-k35',
 'XLTEST-n3334-k1011',
 'XLTEST-n3408-k627',
 'XLTEST-n3484-k291',
 'XLTEST-n3561-k54',
 'XLTEST-n3640-k144',
 'XLTEST-n3721-k197',
 'XLTEST-n3804-k254',
 'XLTEST-n3888-k548',
 'XLTEST-n3975-k489',
 'XLTEST-n4063-k944',
 'XLTEST-n4153-k218',
 'XLTEST-n4245-k164',
 'XLTEST-n4340-k33',
 'XLTEST-n4436-k335',
 'XLTEST-n4535-k1092',
 'XLTEST-n4635-k313',
 'XLTEST-n4738-k456',
 'XLTEST-n4844-k45',
 'XLTEST-n4951-k225',
 'XLTEST-n5061-k951',
 'XLTEST-n5174-k170',
 'XLTEST-n5288-k482',
 'XLTEST-n5406-k29',
 'XLTEST-n5526-k321',
 'XLTEST-n5649-k365',
 'XLTEST-n5774-k885',
 'XLTEST-n5902-k126',
 'XLTEST-n6034-k1234',
 'XLTEST-n6168-k554',
 'XLTEST-n6305-k58',
 'XLTEST-n6445-k189',
 'XLTEST-n6588-k267',
 'XLTEST-n6734-k1123',
 'XLTEST-n6884-k434',
 'XLTEST-n7037-k2302',
 'XLTEST-n7193-k157',
 'XLTEST-n7353-k77',
 'XLTEST-n7516-k1223',
 'XLTEST-n7683-k1624',
 'XLTEST-n7854-k395',
 'XLTEST-n8028-k986',
 'XLTEST-n8207-k649',
 'XLTEST-n8389-k1106',
 'XLTEST-n8575-k343',
 'XLTEST-n8766-k154',
 'XLTEST-n8960-k2144',
 'XLTEST-n9160-k364',
 'XLTEST-n9363-k744',
 'XLTEST-n9571-k980',
 'XLTEST-n9784-k890',
 'XLTEST-n10001-k806']

In [5]:
cur_instance_names = instance_names[50:]

result_dir = '../remote_results/test-continue-XLTEST'
plot_dir = '../figures/continue-XLTEST'

df_1day = load_results_dataframe(cur_instance_names, algorithm_names, base_dir=result_dir, time_limit=86400)
df_4day = load_results_dataframe(cur_instance_names, algorithm_names, base_dir=result_dir, time_limit=4 * 86400)

--- 开始加载数据 (Time Limit: 86400) ---
--- 数据加载完成 ---
--- 开始加载数据 (Time Limit: 345600) ---
--- 数据加载完成 ---

In [6]:
cur_instance_names = instance_names[50:]
cur_instance_names

['XLTEST-n3408-k627',
 'XLTEST-n3484-k291',
 'XLTEST-n3561-k54',
 'XLTEST-n3640-k144',
 'XLTEST-n3721-k197',
 'XLTEST-n3804-k254',
 'XLTEST-n3888-k548',
 'XLTEST-n3975-k489',
 'XLTEST-n4063-k944',
 'XLTEST-n4153-k218',
 'XLTEST-n4245-k164',
 'XLTEST-n4340-k33',
 'XLTEST-n4436-k335',
 'XLTEST-n4535-k1092',
 'XLTEST-n4635-k313',
 'XLTEST-n4738-k456',
 'XLTEST-n4844-k45',
 'XLTEST-n4951-k225',
 'XLTEST-n5061-k951',
 'XLTEST-n5174-k170',
 'XLTEST-n5288-k482',
 'XLTEST-n5406-k29',
 'XLTEST-n5526-k321',
 'XLTEST-n5649-k365',
 'XLTEST-n5774-k885',
 'XLTEST-n5902-k126',
 'XLTEST-n6034-k1234',
 'XLTEST-n6168-k554',
 'XLTEST-n6305-k58',
 'XLTEST-n6445-k189',
 'XLTEST-n6588-k267',
 'XLTEST-n6734-k1123',
 'XLTEST-n6884-k434',
 'XLTEST-n7037-k2302',
 'XLTEST-n7193-k157',
 'XLTEST-n7353-k77',
 'XLTEST-n7516-k1223',
 'XLTEST-n7683-k1624',
 'XLTEST-n7854-k395',
 'XLTEST-n8028-k986',
 'XLTEST-n8207-k649',
 'XLTEST-n8389-k1106',
 'XLTEST-n8575-k343',
 'XLTEST-n8766-k154',
 'XLTEST-n8960-k2144',
 'XLTEST-n9160-k364',
 'XLTEST-n9363-k744',
 'XLTEST-n9571-k980',
 'XLTEST-n9784-k890',
 'XLTEST-n10001-k806']

In [7]:
df_1day

                    AILS2_EoH_Omega2_continue.jar        BKS
XLTEST-n3408-k627                        526020.0   525901.0
XLTEST-n3484-k291                        566032.0   566168.0
XLTEST-n3561-k54                          63447.0    63448.0
XLTEST-n3640-k144                        138226.0   138202.0
XLTEST-n3721-k197                        264565.0   264587.0
XLTEST-n3804-k254                        464935.0   464971.0
XLTEST-n3888-k548                        453878.0   453733.0
XLTEST-n3975-k489                        420046.0   420075.0
XLTEST-n4063-k944                        932227.0   932237.0
XLTEST-n4153-k218                        358091.0   358159.0
XLTEST-n4245-k164                        192358.0   192339.0
XLTEST-n4340-k33                          70112.0    70104.0
XLTEST-n4436-k335                        280427.0   280473.0
XLTEST-n4535-k1092                      1625802.0  1625971.0
XLTEST-n4635-k313                        256750.0   256869.0
XLTEST-n4738-k456                        381971.0   381943.0
XLTEST-n4844-k45                          66721.0    66716.0
XLTEST-n4951-k225                        383902.0   383943.0
XLTEST-n5061-k951                        666069.0   666129.0
XLTEST-n5174-k170                        306268.0   306166.0
XLTEST-n5288-k482                        426312.0   426392.0
XLTEST-n5406-k29                          44268.0    43985.0
XLTEST-n5526-k321                        356780.0   356738.0
XLTEST-n5649-k365                        589500.0   589437.0
XLTEST-n5774-k885                        672586.0   672578.0
XLTEST-n5902-k126                        131264.0   131212.0
XLTEST-n6034-k1234                       990986.0   990956.0
XLTEST-n6168-k554                       1229611.0  1229706.0
XLTEST-n6305-k58                         122998.0   123076.0
XLTEST-n6445-k189                         83954.0    84011.0
XLTEST-n6588-k267                        320112.0   320119.0
XLTEST-n6734-k1123                       895167.0   895135.0
XLTEST-n6884-k434                        491715.0   491686.0
XLTEST-n7037-k2302                      3429272.0  3428512.0
XLTEST-n7193-k157                        170803.0   170851.0
XLTEST-n7353-k77                          79543.0    79532.0
XLTEST-n7516-k1223                      1909956.0  1910056.0
XLTEST-n7683-k1624                      1680729.0  1680813.0
XLTEST-n7854-k395                        633803.0   633916.0
XLTEST-n8028-k986                        806788.0   806736.0
XLTEST-n8207-k649                        845663.0   845698.0
XLTEST-n8389-k1106                      1737486.0  1737438.0
XLTEST-n8575-k343                        231379.0   231421.0
XLTEST-n8766-k154                        251533.0   251485.0
XLTEST-n8960-k2144                      1969606.0  1968728.0
XLTEST-n9160-k364                        454887.0   454933.0
XLTEST-n9363-k744                        872006.0   872233.0
XLTEST-n9571-k980                       1360116.0  1359967.0
XLTEST-n9784-k890                        724141.0   724146.0
XLTEST-n10001-k806                            NaN   656398.0

In [8]:
df_4day

                    AILS2_EoH_Omega2_continue.jar        BKS
XLTEST-n3408-k627                        526020.0   525901.0
XLTEST-n3484-k291                        566032.0   566168.0
XLTEST-n3561-k54                          63447.0    63448.0
XLTEST-n3640-k144                        138226.0   138202.0
XLTEST-n3721-k197                        264565.0   264587.0
XLTEST-n3804-k254                        464935.0   464971.0
XLTEST-n3888-k548                        453878.0   453733.0
XLTEST-n3975-k489                        420046.0   420075.0
XLTEST-n4063-k944                        932227.0   932237.0
XLTEST-n4153-k218                        358091.0   358159.0
XLTEST-n4245-k164                        192358.0   192339.0
XLTEST-n4340-k33                          70112.0    70104.0
XLTEST-n4436-k335                        280427.0   280473.0
XLTEST-n4535-k1092                      1625802.0  1625971.0
XLTEST-n4635-k313                        256750.0   256869.0
XLTEST-n4738-k456                        381971.0   381943.0
XLTEST-n4844-k45                          66721.0    66716.0
XLTEST-n4951-k225                        383902.0   383943.0
XLTEST-n5061-k951                        666069.0   666129.0
XLTEST-n5174-k170                        306268.0   306166.0
XLTEST-n5288-k482                        426312.0   426392.0
XLTEST-n5406-k29                          44268.0    43985.0
XLTEST-n5526-k321                        356780.0   356738.0
XLTEST-n5649-k365                        589500.0   589437.0
XLTEST-n5774-k885                        672586.0   672578.0
XLTEST-n5902-k126                        131264.0   131212.0
XLTEST-n6034-k1234                       990986.0   990956.0
XLTEST-n6168-k554                       1229611.0  1229706.0
XLTEST-n6305-k58                         122998.0   123076.0
XLTEST-n6445-k189                         83954.0    84011.0
XLTEST-n6588-k267                        320112.0   320119.0
XLTEST-n6734-k1123                       895167.0   895135.0
XLTEST-n6884-k434                        491715.0   491686.0
XLTEST-n7037-k2302                      3429272.0  3428512.0
XLTEST-n7193-k157                        170803.0   170851.0
XLTEST-n7353-k77                          79543.0    79532.0
XLTEST-n7516-k1223                      1909956.0  1910056.0
XLTEST-n7683-k1624                      1680729.0  1680813.0
XLTEST-n7854-k395                        633803.0   633916.0
XLTEST-n8028-k986                        806788.0   806736.0
XLTEST-n8207-k649                        845663.0   845698.0
XLTEST-n8389-k1106                      1737486.0  1737438.0
XLTEST-n8575-k343                        231379.0   231421.0
XLTEST-n8766-k154                        251533.0   251485.0
XLTEST-n8960-k2144                      1969606.0  1968728.0
XLTEST-n9160-k364                        454887.0   454933.0
XLTEST-n9363-k744                        872006.0   872233.0
XLTEST-n9571-k980                       1360116.0  1359967.0
XLTEST-n9784-k890                        724141.0   724146.0
XLTEST-n10001-k806                            NaN   656398.0

In [15]:
method_col = 'AILS2_EoH_Omega2_continue.jar'
df_1day['Gap'] = (df_1day[method_col] - df_1day['BKS']) / df_1day['BKS'] * 100
display(df_1day)

                    AILS2_EoH_Omega2_continue.jar        BKS       Gap
XLTEST-n3408-k627                        526020.0   525901.0  0.022628
XLTEST-n3484-k291                        566032.0   566168.0 -0.024021
XLTEST-n3561-k54                          63447.0    63448.0 -0.001576
XLTEST-n3640-k144                        138226.0   138202.0  0.017366
XLTEST-n3721-k197                        264565.0   264587.0 -0.008315
XLTEST-n3804-k254                        464935.0   464971.0 -0.007742
XLTEST-n3888-k548                        453878.0   453733.0  0.031957
XLTEST-n3975-k489                        420046.0   420075.0 -0.006904
XLTEST-n4063-k944                        932227.0   932237.0 -0.001073
XLTEST-n4153-k218                        358091.0   358159.0 -0.018986
XLTEST-n4245-k164                        192358.0   192339.0  0.009878
XLTEST-n4340-k33                          70112.0    70104.0  0.011412
XLTEST-n4436-k335                        280427.0   280473.0 -0.016401
XLTEST-n4535-k1092                      1625802.0  1625971.0 -0.010394
XLTEST-n4635-k313                        256750.0   256869.0 -0.046327
XLTEST-n4738-k456                        381971.0   381943.0  0.007331
XLTEST-n4844-k45                          66721.0    66716.0  0.007494
XLTEST-n4951-k225                        383902.0   383943.0 -0.010679
XLTEST-n5061-k951                        666069.0   666129.0 -0.009007
XLTEST-n5174-k170                        306268.0   306166.0  0.033315
XLTEST-n5288-k482                        426312.0   426392.0 -0.018762
XLTEST-n5406-k29                          44268.0    43985.0  0.643401
XLTEST-n5526-k321                        356780.0   356738.0  0.011773
XLTEST-n5649-k365                        589500.0   589437.0  0.010688
XLTEST-n5774-k885                        672586.0   672578.0  0.001189
XLTEST-n5902-k126                        131264.0   131212.0  0.039631
XLTEST-n6034-k1234                       990986.0   990956.0  0.003027
XLTEST-n6168-k554                       1229611.0  1229706.0 -0.007725
XLTEST-n6305-k58                         122998.0   123076.0 -0.063375
XLTEST-n6445-k189                         83954.0    84011.0 -0.067848
XLTEST-n6588-k267                        320112.0   320119.0 -0.002187
XLTEST-n6734-k1123                       895167.0   895135.0  0.003575
XLTEST-n6884-k434                        491715.0   491686.0  0.005898
XLTEST-n7037-k2302                      3429272.0  3428512.0  0.022167
XLTEST-n7193-k157                        170803.0   170851.0 -0.028095
XLTEST-n7353-k77                          79543.0    79532.0  0.013831
XLTEST-n7516-k1223                      1909956.0  1910056.0 -0.005235
XLTEST-n7683-k1624                      1680729.0  1680813.0 -0.004998
XLTEST-n7854-k395                        633803.0   633916.0 -0.017826
XLTEST-n8028-k986                        806788.0   806736.0  0.006446
XLTEST-n8207-k649                        845663.0   845698.0 -0.004139
XLTEST-n8389-k1106                      1737486.0  1737438.0  0.002763
XLTEST-n8575-k343                        231379.0   231421.0 -0.018149
XLTEST-n8766-k154                        251533.0   251485.0  0.019087
XLTEST-n8960-k2144                      1969606.0  1968728.0  0.044597
XLTEST-n9160-k364                        454887.0   454933.0 -0.010111
XLTEST-n9363-k744                        872006.0   872233.0 -0.026025
XLTEST-n9571-k980                       1360116.0  1359967.0  0.010956
XLTEST-n9784-k890                        724141.0   724146.0 -0.000690
XLTEST-n10001-k806                            NaN   656398.0       NaN

In [16]:
df_cleaned = df_1day.drop(index='XLTEST-n5406-k29', errors='ignore')
average_gap = df_cleaned['Gap'].mean()
print(average_gap)

-0.0020745887448031923

In [11]:

plot_gap_scatter(df_1day, output_dir=f'{plot_dir}/continue_1day_scatter.png', point_alpha=0.5, point_size=20, )

--- 开始绘制 Gap 散点图 ---

图像已保存至: ../figures/continue-XLTEST/continue_1day_scatter.png

In [31]:
plot_gap_scatter(df_4day, output_dir=f'{plot_dir}/continue_4day_scatter.png', point_alpha=0.5, point_size=20, )

--- 开始绘制 Gap 散点图 ---

图像已保存至: ../figures/continue-XLTEST/continue_4day_scatter.png

In [32]:
# instance_dir = '../XLTEST'
# instance_names = [i.split('.')[0] for i in os.listdir(instance_dir)]
# plot_gap_scatter_from_sol(cur_instance_names, algorithm_names, base_dir=result_dir, output_dir=plot_dir, point_alpha=0.5, point_size=20)

In [33]:
# from plot_utils import get_average_gap_statistics
# 
# df_avg_gap = get_average_gap_statistics(cur_instance_names, algorithm_names, base_dir=result_dir, baseline='Mahdi_baseline')
# df_avg_gap

In [9]:
get_rank_statistics(df_1day)

--- 开始计算排名统计 ---
Rank_Label                     Strict Rank 1  Rank 2
Method
AILS2_EoH_Omega2_continue.jar             26      23
BKS                                       24      26

Rank_Label                     Strict Rank 1  Rank 2
Method
AILS2_EoH_Omega2_continue.jar             26      23
BKS                                       24      26

In [35]:
get_rank_statistics(df_4day)

--- 开始计算排名统计 ---
Rank_Label                        Strict Rank 1  Tied Rank 1  Rank 2  Rank 3  \
Method
AILS2_EoH_Acc_large_continue.jar              1            1       8       6
AILS2_EoH_Omega2_continue.jar                 6            0      19      10
AILSII_continue_1                            26            1       8       8
BKS                                          12            1       7      11
EoH_Acc                                       3            1      11      16
EoH_Omega                                     0            0       2       1

Rank_Label                        Rank 4  Rank 5  Rank 6
Method
AILS2_EoH_Acc_large_continue.jar      20      13       0
AILS2_EoH_Omega2_continue.jar          8       6       0
AILSII_continue_1                      3       4       0
BKS                                    5      13       1
EoH_Acc                               12       6       0
EoH_Omega                              4       3      40

Rank_Label,Strict Rank 1,Tied Rank 1,Rank 2,Rank 3,Rank 4,Rank 5,Rank 6
Method,,,,,,,
AILS2_EoH_Acc_large_continue.jar,1,1,8,6,20,13,0
AILS2_EoH_Omega2_continue.jar,6,0,19,10,8,6,0
AILSII_continue_1,26,1,8,8,3,4,0
BKS,12,1,7,11,5,13,1
EoH_Acc,3,1,11,16,12,6,0
EoH_Omega,0,0,2,1,4,3,40

In [10]:
get_average_gap_statistics(df_1day)

--- 开始计算平均 Gap (Baseline: Best Found) ---
                          Method  Average Gap (%)
1                            BKS         0.008735
0  AILS2_EoH_Omega2_continue.jar         0.020008

                          Method  Average Gap (%)
1                            BKS         0.008735
0  AILS2_EoH_Omega2_continue.jar         0.020008

In [37]:
get_average_gap_statistics(df_4day)

--- 开始计算平均 Gap (Baseline: Best Found) ---
                             Method  Average Gap (%)
3                               BKS         0.015170
0                 AILSII_continue_1         0.020219
2     AILS2_EoH_Omega2_continue.jar         0.026575
4                           EoH_Acc         0.028734
1  AILS2_EoH_Acc_large_continue.jar         0.029441
5                         EoH_Omega         0.058895

                             Method  Average Gap (%)
3                               BKS         0.015170
0                 AILSII_continue_1         0.020219
2     AILS2_EoH_Omega2_continue.jar         0.026575
4                           EoH_Acc         0.028734
1  AILS2_EoH_Acc_large_continue.jar         0.029441
5                         EoH_Omega         0.058895

In [38]:
import os
import glob
import pandas as pd
from collections import deque

def get_max_time_from_csv(file_path):
    """
    读取CSV文件的最后一行以提取最大时间。
    如果文件为空，返回 0。
    """
    # 1. 检查文件是否为空
    if os.path.getsize(file_path) == 0:
        return 0.0

    try:
        # 2. 打开文件并只读取最后一行 (使用 deque 只保留最后1行)
        with open(file_path, 'r', encoding='utf-8') as f:
            # deque(f, 1) 会高效地只抓取最后一行
            last_line_gen = deque(f, maxlen=1)
            
            if not last_line_gen: # 双重检查：如果文件有大小但内容为空（如只有换行符）
                return 0.0
            
            last_line = last_line_gen[0].strip()
            
            # 3. 解析数据: {time};{fitness}
            # 假设格式总是分号分隔，且第一列是时间
            if not last_line:
                return 0.0
                
            time_str = last_line.split(';')[0]
            return float(time_str)
            
    except Exception as e:
        print(f"处理文件 {os.path.basename(file_path)} 时出错: {e}")
        return 0.0 # 出错时默认返回0，或者根据需求改为 None

In [39]:


# ================= 配置路径 =================
# ===========================================

def analysis_max_times(target_path):
    method_name = os.path.basename(target_path)
    
    # 获取所有csv文件
    csv_files = glob.glob(os.path.join(target_path, "*.csv"))
    data_list = []
    
    print(f"正在处理 {len(csv_files)} 个文件...")
    
    for file in csv_files:
        max_time = get_max_time_from_csv(file)
        # 记录文件名（不含路径）和最大时间
        data_list.append({
            'filename': os.path.basename(file),
            'max_time': max_time
        })
    
    # 1. 生成 DataFrame
    df = pd.DataFrame(data_list)
    
    # 按文件名排序（可选，方便查看）
    df = df.sort_values(by='filename').reset_index(drop=True)
    
    print("--- 结果预览 (前5行) ---")
    print(df.head())
    
    print(f"\n--- 统计信息 - {method_name} ---")
    # 2. 做个统计 (均值、最大值、最小值、分位数等)
    stats = df['max_time'].describe()
    print(stats)
    
    zero_count = (df['max_time'] == 0).sum()
    print(f"\n完全无提升instance个数: {zero_count} / {len(df)}")

# 如果你想查看具体的时间分布情况
# print(df['max_time'].value_counts(bins=10))

In [40]:
target_path = f'{result_dir}/AILS_continue_Mahdi'  # 请修改为你的实际文件夹路径
analysis_max_times(target_path)

正在处理 0 个文件...

KeyError: 'filename'