In [1]:
%load_ext autoreload
%autoreload 2

import os
import pandas as pd
import matplotlib.pyplot as plt
from plot_utils import plot_search_curves, plot_best_fitness, plot_gap_scatter, plot_gap_scatter_from_sol, get_fitness_table
%matplotlib notebook

In [2]:
from plot_utils import plot_best_fitness

algorithm_names = [
    'AILSII_origin_5d'
]

instance_dir = '../XLTEST'
# instance_dir = '../XLDemo'

instance_names = [i.split('.')[0] for i in os.listdir(instance_dir) if i.endswith('.vrp')]
# instance_names = [instance_names[i] for i in [70, 80, 90, 97]]

In [14]:
import re
def extract_n_value(filename):
    # 正则表达式解释：
    # n      : 匹配字符 'n'
    # (\d+)  : 捕获组，匹配一个或多个数字
    match = re.search(r'n(\d+)', filename)
    if match:
        return int(match.group(1)) # 返回整数类型以便正确排序
    return 0 # 如果没找到，返回0排在最后

instance_names = sorted(instance_names, key=extract_n_value, reverse=False)

In [3]:
instance_names

['XLTEST-n3561-k54',
 'XLTEST-n6884-k434',
 'XLTEST-n2261-k168',
 'XLTEST-n3804-k254',
 'XLTEST-n2587-k114',
 'XLTEST-n7516-k1223',
 'XLTEST-n1468-k47',
 'XLTEST-n2121-k107',
 'XLTEST-n6734-k1123',
 'XLTEST-n7683-k1624',
 'XLTEST-n2867-k169',
 'XLTEST-n1188-k72',
 'XLTEST-n5174-k170',
 'XLTEST-n2914-k852',
 'XLTEST-n4245-k164',
 'XLTEST-n3287-k35',
 'XLTEST-n2494-k624',
 'XLTEST-n1281-k42',
 'XLTEST-n4951-k225',
 'XLTEST-n3721-k197',
 'XLTEST-n7193-k157',
 'XLTEST-n2354-k217',
 'XLTEST-n1234-k252',
 'XLTEST-n5061-k951',
 'XLTEST-n3334-k1011',
 'XLTEST-n2447-k199',
 'XLTEST-n6034-k1234',
 'XLTEST-n4436-k335',
 'XLTEST-n2774-k349',
 'XLTEST-n6168-k554',
 'XLTEST-n2681-k15',
 'XLTEST-n1934-k107',
 'XLTEST-n3101-k685',
 'XLTEST-n5902-k126',
 'XLTEST-n1841-k37',
 'XLTEST-n6588-k267',
 'XLTEST-n1141-k75',
 'XLTEST-n4535-k1092',
 'XLTEST-n3054-k306',
 'XLTEST-n3194-k93',
 'XLTEST-n1094-k9',
 'XLTEST-n1794-k405',
 'XLTEST-n3975-k489',
 'XLTEST-n8766-k154',
 'XLTEST-n1328-k115',
 'XLTEST-n1701-k10',
 'XLTEST-n8389-k1106',
 'XLTEST-n1048-k139',
 'XLTEST-n7854-k395',
 'XLTEST-n4063-k944',
 'XLTEST-n1561-k156',
 'XLTEST-n3484-k291',
 'XLTEST-n1888-k206',
 'XLTEST-n3147-k215',
 'XLTEST-n5774-k885',
 'XLTEST-n1514-k125',
 'XLTEST-n7353-k77',
 'XLTEST-n9784-k890',
 'XLTEST-n5406-k29',
 'XLTEST-n2307-k13',
 'XLTEST-n2074-k225',
 'XLTEST-n4153-k218',
 'XLTEST-n6305-k58',
 'XLTEST-n3888-k548',
 'XLTEST-n4340-k33',
 'XLTEST-n8028-k986',
 'XLTEST-n5649-k365',
 'XLTEST-n10001-k806',
 'XLTEST-n8575-k343',
 'XLTEST-n9571-k980',
 'XLTEST-n4844-k45',
 'XLTEST-n2028-k406',
 'XLTEST-n2401-k16',
 'XLTEST-n8207-k649',
 'XLTEST-n2634-k380',
 'XLTEST-n9160-k364',
 'XLTEST-n3408-k627',
 'XLTEST-n2727-k175',
 'XLTEST-n3640-k144',
 'XLTEST-n4635-k313',
 'XLTEST-n8960-k2144',
 'XLTEST-n6445-k189',
 'XLTEST-n2961-k73',
 'XLTEST-n5288-k482',
 'XLTEST-n1981-k146',
 'XLTEST-n2821-k336',
 'XLTEST-n1748-k293',
 'XLTEST-n2541-k92',
 'XLTEST-n3241-k628',
 'XLTEST-n2214-k61',
 'XLTEST-n1374-k71',
 'XLTEST-n1608-k488',
 'XLTEST-n1421-k12',
 'XLTEST-n4738-k456',
 'XLTEST-n9363-k744',
 'XLTEST-n7037-k2302',
 'XLTEST-n1654-k322',
 'XLTEST-n5526-k321',
 'XLTEST-n3007-k152',
 'XLTEST-n2168-k625']

In [4]:
cur_instance_names = instance_names

result_dir = '../remote_results/test-5days'
plot_dir = '../figures/5days'

df = get_fitness_table(cur_instance_names, algorithm_names, base_dir=result_dir)
df

--- 开始生成 Fitness 表格 (基于 .sol 文件) ---

--- Fitness 表格预览 ---
                   AILSII_origin_5d
Instance
XLTEST-n3561-k54            63478.0
XLTEST-n6884-k434          491978.0
XLTEST-n2261-k168          281586.0
XLTEST-n3804-k254          465074.0
XLTEST-n2587-k114          193937.0

                    AILSII_origin_5d
Instance
XLTEST-n3561-k54             63478.0
XLTEST-n6884-k434           491978.0
XLTEST-n2261-k168           281586.0
XLTEST-n3804-k254           465074.0
XLTEST-n2587-k114           193937.0
...                              ...
XLTEST-n7037-k2302         3429272.0
XLTEST-n1654-k322           668003.0
XLTEST-n5526-k321           357448.0
XLTEST-n3007-k152           249704.0
XLTEST-n2168-k625           530012.0

[100 rows x 1 columns]

In [12]:
# base_col = df.columns[0]  # 第一列 (作为基准)
# target_col = df.columns[1] # 第二列 (用于对比)
# 
# # 2. 定义新列的名称 (例如: Gap_MethodB_vs_MethodA)
# gap_col_name = f'Gap_{target_col}_vs_{base_col}'
# 
# # 3. 计算 Gap: ((Target - Base) / Base) * 100
# df[gap_col_name] = ((df[target_col] - df[base_col]) / df[base_col]) * 100
# 
# df

In [17]:
for instance in cur_instance_names:
    plot_best_fitness(instance, algorithm_names, base_dir=result_dir, output_dir=plot_dir)

--- 开始绘制【最佳Fitness】曲线: XLTEST-n1048-k139 ---
信息: 文件 None 未找到, 跳过。
AILSII_continue_1: 2 entries | best fitness: 124174.0
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.1/XLTEST-n1048-k139_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.5/XLTEST-n1048-k139_1.csv 为空, 跳过。
AILS2_Eta_Cycle_continue_1800_0.05: 23 entries | best fitness: 0.0137
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.25/XLTEST-n1048-k139_1.csv 为空, 跳过。
AILS2_Eta_Cycle_continue_1800_0.75: 29 entries | best fitness: 0.017
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_1/XLTEST-n1048-k139_1.csv 为空, 跳过。
AILS2_Eta_Cycle_continue_3600_0.1: 29 entries | best fitness: 0.0186
AILS2_Eta_Cycle_continue_3600_0.5: 17 entries | best fitness: 0.0176
AILS2_Eta_Cycle_continue_3600_0.05: 24 entries | best fitness: 0.0343
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_0.25/XLTEST-n1048-k139_1.csv 为空, 跳过。
AILS2_Eta_Cycle_continue_3600_0.75: 30 entries | best fitness: 0.01
AILS2_Eta_Cycle_continue_3600_1: 23 entries | best fitness: 0.0313
--- 绘图完成: XLTEST-n1048-k139, 图像已保存至 ../figures/continue-XLDemo/plot_best_fitness_XLTEST-n1048-k139.png ---

--- 开始绘制【最佳Fitness】曲线: XLTEST-n2168-k625 ---
信息: 文件 None 未找到, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILSII_continue_1/XLTEST-n2168-k625_1.csv 为空, 跳过。
AILS2_Eta_Cycle_continue_1800_0.1: 107 entries | best fitness: 0.0148
AILS2_Eta_Cycle_continue_1800_0.5: 100 entries | best fitness: 0.0162
AILS2_Eta_Cycle_continue_1800_0.05: 124 entries | best fitness: 0.0193
AILS2_Eta_Cycle_continue_1800_0.25: 85 entries | best fitness: 0.0171
AILS2_Eta_Cycle_continue_1800_0.75: 97 entries | best fitness: 0.0131
AILS2_Eta_Cycle_continue_1800_1: 38 entries | best fitness: 0.0259
AILS2_Eta_Cycle_continue_3600_0.1: 118 entries | best fitness: 0.0177
AILS2_Eta_Cycle_continue_3600_0.5: 84 entries | best fitness: 0.011
AILS2_Eta_Cycle_continue_3600_0.05: 57 entries | best fitness: 0.0199
AILS2_Eta_Cycle_continue_3600_0.25: 109 entries | best fitness: 0.0244
AILS2_Eta_Cycle_continue_3600_0.75: 96 entries | best fitness: 0.0241
AILS2_Eta_Cycle_continue_3600_1: 80 entries | best fitness: 0.0207
--- 绘图完成: XLTEST-n2168-k625, 图像已保存至 ../figures/continue-XLDemo/plot_best_fitness_XLTEST-n2168-k625.png ---

--- 开始绘制【最佳Fitness】曲线: XLTEST-n3101-k685 ---
信息: 文件 None 未找到, 跳过。
AILSII_continue_1: 26 entries | best fitness: 562936.0
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.1/XLTEST-n3101-k685_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.5/XLTEST-n3101-k685_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.05/XLTEST-n3101-k685_1.csv 为空, 跳过。
AILS2_Eta_Cycle_continue_1800_0.25: 48 entries | best fitness: 0.0154
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.75/XLTEST-n3101-k685_1.csv 为空, 跳过。
AILS2_Eta_Cycle_continue_1800_1: 3 entries | best fitness: 0.0139
AILS2_Eta_Cycle_continue_3600_0.1: 1 entries | best fitness: 1.0
AILS2_Eta_Cycle_continue_3600_0.5: 17 entries | best fitness: 0.0108
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_0.05/XLTEST-n3101-k685_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_0.25/XLTEST-n3101-k685_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_0.75/XLTEST-n3101-k685_1.csv 为空, 跳过。
AILS2_Eta_Cycle_continue_3600_1: 3 entries | best fitness: 0.0111
--- 绘图完成: XLTEST-n3101-k685, 图像已保存至 ../figures/continue-XLDemo/plot_best_fitness_XLTEST-n3101-k685.png ---

--- 开始绘制【最佳Fitness】曲线: XLTEST-n4245-k164 ---
信息: 文件 None 未找到, 跳过。
AILSII_continue_1: 50 entries | best fitness: 192302.0
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.1/XLTEST-n4245-k164_1.csv 为空, 跳过。
AILS2_Eta_Cycle_continue_1800_0.5: 1 entries | best fitness: 1.0
AILS2_Eta_Cycle_continue_1800_0.05: 12 entries | best fitness: 0.0103
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.25/XLTEST-n4245-k164_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.75/XLTEST-n4245-k164_1.csv 为空, 跳过。
AILS2_Eta_Cycle_continue_1800_1: 11 entries | best fitness: 0.0115
AILS2_Eta_Cycle_continue_3600_0.1: 12 entries | best fitness: 0.01
AILS2_Eta_Cycle_continue_3600_0.5: 19 entries | best fitness: 0.012
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_0.05/XLTEST-n4245-k164_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_0.25/XLTEST-n4245-k164_1.csv 为空, 跳过。
AILS2_Eta_Cycle_continue_3600_0.75: 41 entries | best fitness: 0.01
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_1/XLTEST-n4245-k164_1.csv 为空, 跳过。
--- 绘图完成: XLTEST-n4245-k164, 图像已保存至 ../figures/continue-XLDemo/plot_best_fitness_XLTEST-n4245-k164.png ---

--- 开始绘制【最佳Fitness】曲线: XLTEST-n5174-k170 ---
信息: 文件 None 未找到, 跳过。
AILSII_continue_1: 121 entries | best fitness: 306239.0
AILS2_Eta_Cycle_continue_1800_0.1: 4 entries | best fitness: 0.01
AILS2_Eta_Cycle_continue_1800_0.5: 50 entries | best fitness: 0.01
AILS2_Eta_Cycle_continue_1800_0.05: 19 entries | best fitness: 0.0125
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.25/XLTEST-n5174-k170_1.csv 为空, 跳过。
AILS2_Eta_Cycle_continue_1800_0.75: 144 entries | best fitness: 0.0112
AILS2_Eta_Cycle_continue_1800_1: 47 entries | best fitness: 0.0136
AILS2_Eta_Cycle_continue_3600_0.1: 74 entries | best fitness: 0.0127
AILS2_Eta_Cycle_continue_3600_0.5: 66 entries | best fitness: 0.0184
AILS2_Eta_Cycle_continue_3600_0.05: 64 entries | best fitness: 0.0135
AILS2_Eta_Cycle_continue_3600_0.25: 43 entries | best fitness: 0.0134
AILS2_Eta_Cycle_continue_3600_0.75: 4 entries | best fitness: 0.0121
AILS2_Eta_Cycle_continue_3600_1: 23 entries | best fitness: 0.01
--- 绘图完成: XLTEST-n5174-k170, 图像已保存至 ../figures/continue-XLDemo/plot_best_fitness_XLTEST-n5174-k170.png ---

--- 开始绘制【最佳Fitness】曲线: XLTEST-n5649-k365 ---
信息: 文件 None 未找到, 跳过。
AILSII_continue_1: 410 entries | best fitness: 589338.0
AILS2_Eta_Cycle_continue_1800_0.1: 142 entries | best fitness: 0.0131
AILS2_Eta_Cycle_continue_1800_0.5: 251 entries | best fitness: 0.012
AILS2_Eta_Cycle_continue_1800_0.05: 187 entries | best fitness: 0.0124
AILS2_Eta_Cycle_continue_1800_0.25: 210 entries | best fitness: 0.01
AILS2_Eta_Cycle_continue_1800_0.75: 218 entries | best fitness: 0.0114
AILS2_Eta_Cycle_continue_1800_1: 67 entries | best fitness: 0.01
AILS2_Eta_Cycle_continue_3600_0.1: 219 entries | best fitness: 0.0163
AILS2_Eta_Cycle_continue_3600_0.5: 63 entries | best fitness: 0.01
AILS2_Eta_Cycle_continue_3600_0.05: 220 entries | best fitness: 0.0161
AILS2_Eta_Cycle_continue_3600_0.25: 264 entries | best fitness: 0.0133
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_0.75/XLTEST-n5649-k365_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_1/XLTEST-n5649-k365_1.csv 为空, 跳过。
--- 绘图完成: XLTEST-n5649-k365, 图像已保存至 ../figures/continue-XLDemo/plot_best_fitness_XLTEST-n5649-k365.png ---

--- 开始绘制【最佳Fitness】曲线: XLTEST-n6034-k1234 ---
信息: 文件 None 未找到, 跳过。
AILSII_continue_1: 195 entries | best fitness: 990913.0
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.1/XLTEST-n6034-k1234_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.5/XLTEST-n6034-k1234_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.05/XLTEST-n6034-k1234_1.csv 为空, 跳过。
AILS2_Eta_Cycle_continue_1800_0.25: 15 entries | best fitness: 0.01
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.75/XLTEST-n6034-k1234_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_1/XLTEST-n6034-k1234_1.csv 为空, 跳过。
AILS2_Eta_Cycle_continue_3600_0.1: 155 entries | best fitness: 0.0111
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_0.5/XLTEST-n6034-k1234_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_0.05/XLTEST-n6034-k1234_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_0.25/XLTEST-n6034-k1234_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_0.75/XLTEST-n6034-k1234_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_1/XLTEST-n6034-k1234_1.csv 为空, 跳过。
--- 绘图完成: XLTEST-n6034-k1234, 图像已保存至 ../figures/continue-XLDemo/plot_best_fitness_XLTEST-n6034-k1234.png ---

--- 开始绘制【最佳Fitness】曲线: XLTEST-n8575-k343 ---
信息: 文件 None 未找到, 跳过。
AILSII_continue_1: 135 entries | best fitness: 231345.0
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.1/XLTEST-n8575-k343_1.csv 为空, 跳过。
AILS2_Eta_Cycle_continue_1800_0.5: 17 entries | best fitness: 0.01
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.05/XLTEST-n8575-k343_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.25/XLTEST-n8575-k343_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_0.75/XLTEST-n8575-k343_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_1800_1/XLTEST-n8575-k343_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_0.1/XLTEST-n8575-k343_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_0.5/XLTEST-n8575-k343_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_0.05/XLTEST-n8575-k343_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_0.25/XLTEST-n8575-k343_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_0.75/XLTEST-n8575-k343_1.csv 为空, 跳过。
警告: 文件 ../remote_results/test-continue-XLDemo/AILS2_Eta_Cycle_continue_3600_1/XLTEST-n8575-k343_1.csv 为空, 跳过。
--- 绘图完成: XLTEST-n8575-k343, 图像已保存至 ../figures/continue-XLDemo/plot_best_fitness_XLTEST-n8575-k343.png ---

In [18]:
# instance_dir = '../XLTEST'
# instance_names = [i.split('.')[0] for i in os.listdir(instance_dir)]
plot_gap_scatter_from_sol(cur_instance_names, algorithm_names, base_dir=result_dir, output_dir=plot_dir, point_alpha=0.5, point_size=20)

--- 开始绘制 Gap 分析 (基于 .sol 文件) ---

--- Gap 分析完成. 图像已保存至 ../figures/continue-XLDemo/gap_analysis_scatter_sol.png ---

In [19]:
from plot_utils import get_average_gap_statistics

df_avg_gap = get_average_gap_statistics(cur_instance_names, algorithm_names, base_dir=result_dir, baseline='Mahdi_baseline')
df_avg_gap

--- 开始计算平均 Gap (基于 .sol 文件) | Baseline模式: Mahdi_baseline ---

--- 平均 Gap 统计表 ---
                                Method  Average Gap (%)
12                   AILSII_continue_1        -0.000974
13                      Mahdi_baseline         0.000000
7    AILS2_Eta_Cycle_continue_3600_0.1         0.014196
4   AILS2_Eta_Cycle_continue_1800_0.75         0.017242
6   AILS2_Eta_Cycle_continue_3600_0.05         0.019845
0   AILS2_Eta_Cycle_continue_1800_0.05         0.020877
8   AILS2_Eta_Cycle_continue_3600_0.25         0.022411
9    AILS2_Eta_Cycle_continue_3600_0.5         0.023087
3    AILS2_Eta_Cycle_continue_1800_0.5         0.023424
10  AILS2_Eta_Cycle_continue_3600_0.75         0.024515
2   AILS2_Eta_Cycle_continue_1800_0.25         0.026208
11     AILS2_Eta_Cycle_continue_3600_1         0.028313
1    AILS2_Eta_Cycle_continue_1800_0.1         0.028455
5      AILS2_Eta_Cycle_continue_1800_1         0.030226

                                Method  Average Gap (%)
12                   AILSII_continue_1        -0.000974
13                      Mahdi_baseline         0.000000
7    AILS2_Eta_Cycle_continue_3600_0.1         0.014196
4   AILS2_Eta_Cycle_continue_1800_0.75         0.017242
6   AILS2_Eta_Cycle_continue_3600_0.05         0.019845
0   AILS2_Eta_Cycle_continue_1800_0.05         0.020877
8   AILS2_Eta_Cycle_continue_3600_0.25         0.022411
9    AILS2_Eta_Cycle_continue_3600_0.5         0.023087
3    AILS2_Eta_Cycle_continue_1800_0.5         0.023424
10  AILS2_Eta_Cycle_continue_3600_0.75         0.024515
2   AILS2_Eta_Cycle_continue_1800_0.25         0.026208
11     AILS2_Eta_Cycle_continue_3600_1         0.028313
1    AILS2_Eta_Cycle_continue_1800_0.1         0.028455
5      AILS2_Eta_Cycle_continue_1800_1         0.030226

In [20]:
from plot_utils import get_rank_statistics

get_rank_statistics(cur_instance_names, algorithm_names, base_dir=result_dir)

--- 开始统计算法排名情况 (区分 Strict/Tied Rank 1) ---

--- 排名统计表 (Rank Statistics) ---
Rank_Label                          Strict Rank 1  Rank 2  Rank 3  Rank 4  \
Method
AILS2_Eta_Cycle_continue_1800_0.05              1       0       0       1
AILS2_Eta_Cycle_continue_1800_0.1               0       0       1       1
AILS2_Eta_Cycle_continue_1800_0.25              1       0       0       2
AILS2_Eta_Cycle_continue_1800_0.5               0       0       1       0
AILS2_Eta_Cycle_continue_1800_0.75              0       0       1       1
AILS2_Eta_Cycle_continue_1800_1                 0       0       0       1
AILS2_Eta_Cycle_continue_3600_0.05              0       0       1       2
AILS2_Eta_Cycle_continue_3600_0.1               1       0       1       3
AILS2_Eta_Cycle_continue_3600_0.25              0       1       1       1
AILS2_Eta_Cycle_continue_3600_0.5               0       0       1       3
AILS2_Eta_Cycle_continue_3600_0.75              0       2       0       1
AILS2_Eta_Cycle_continue_3600_1                 0       0       0       1
AILSII_continue_1                               4       1       1       0
Mahdi_baseline                                  1       4       0       1

Rank_Label                          Rank 5  Rank 6  Rank 7  Rank 8  Rank 9  \
Method
AILS2_Eta_Cycle_continue_1800_0.05       3       0       1       0       1
AILS2_Eta_Cycle_continue_1800_0.1        1       0       1       1       1
AILS2_Eta_Cycle_continue_1800_0.25       0       0       0       2       2
AILS2_Eta_Cycle_continue_1800_0.5        2       0       3       0       1
AILS2_Eta_Cycle_continue_1800_0.75       1       1       3       1       0
AILS2_Eta_Cycle_continue_1800_1          2       1       1       0       1
AILS2_Eta_Cycle_continue_3600_0.05       1       1       1       1       0
AILS2_Eta_Cycle_continue_3600_0.1        0       3       0       0       0
AILS2_Eta_Cycle_continue_3600_0.25       1       0       1       2       1
AILS2_Eta_Cycle_continue_3600_0.5        2       0       0       1       0
AILS2_Eta_Cycle_continue_3600_0.75       1       0       2       0       0
AILS2_Eta_Cycle_continue_3600_1          4       0       0       1       1
AILSII_continue_1                        0       0       0       1       0
Mahdi_baseline                           0       1       0       0       0

Rank_Label                          Rank 10  Rank 11  Rank 12  Rank 13  \
Method
AILS2_Eta_Cycle_continue_1800_0.05        1        0        0        0
AILS2_Eta_Cycle_continue_1800_0.1         1        0        1        0
AILS2_Eta_Cycle_continue_1800_0.25        0        0        0        1
AILS2_Eta_Cycle_continue_1800_0.5         1        0        0        0
AILS2_Eta_Cycle_continue_1800_0.75        0        0        0        0
AILS2_Eta_Cycle_continue_1800_1           0        0        1        1
AILS2_Eta_Cycle_continue_3600_0.05        0        1        0        0
AILS2_Eta_Cycle_continue_3600_0.1         0        0        0        0
AILS2_Eta_Cycle_continue_3600_0.25        0        0        0        0
AILS2_Eta_Cycle_continue_3600_0.5         0        1        0        0
AILS2_Eta_Cycle_continue_3600_0.75        0        1        0        1
AILS2_Eta_Cycle_continue_3600_1           0        0        0        1
AILSII_continue_1                         0        0        0        0
Mahdi_baseline                            0        0        1        0

Rank_Label                          Rank 14
Method
AILS2_Eta_Cycle_continue_1800_0.05        0
AILS2_Eta_Cycle_continue_1800_0.1         0
AILS2_Eta_Cycle_continue_1800_0.25        0
AILS2_Eta_Cycle_continue_1800_0.5         0
AILS2_Eta_Cycle_continue_1800_0.75        0
AILS2_Eta_Cycle_continue_1800_1           0
AILS2_Eta_Cycle_continue_3600_0.05        0
AILS2_Eta_Cycle_continue_3600_0.1         0
AILS2_Eta_Cycle_continue_3600_0.25        0
AILS2_Eta_Cycle_continue_3600_0.5         0
AILS2_Eta_Cycle_continue_3600_0.75        0
AILS2_Eta_Cycle_continue_3600_1           0
AILSII_continue_1                         1
Mahdi_baseline                            0

Rank_Label,Strict Rank 1,Rank 2,Rank 3,Rank 4,Rank 5,Rank 6,Rank 7,Rank 8,Rank 9,Rank 10,Rank 11,Rank 12,Rank 13,Rank 14
Method,,,,,,,,,,,,,,
AILS2_Eta_Cycle_continue_1800_0.05,1,0,0,1,3,0,1,0,1,1,0,0,0,0
AILS2_Eta_Cycle_continue_1800_0.1,0,0,1,1,1,0,1,1,1,1,0,1,0,0
AILS2_Eta_Cycle_continue_1800_0.25,1,0,0,2,0,0,0,2,2,0,0,0,1,0
AILS2_Eta_Cycle_continue_1800_0.5,0,0,1,0,2,0,3,0,1,1,0,0,0,0
AILS2_Eta_Cycle_continue_1800_0.75,0,0,1,1,1,1,3,1,0,0,0,0,0,0
AILS2_Eta_Cycle_continue_1800_1,0,0,0,1,2,1,1,0,1,0,0,1,1,0
AILS2_Eta_Cycle_continue_3600_0.05,0,0,1,2,1,1,1,1,0,0,1,0,0,0
AILS2_Eta_Cycle_continue_3600_0.1,1,0,1,3,0,3,0,0,0,0,0,0,0,0
AILS2_Eta_Cycle_continue_3600_0.25,0,1,1,1,1,0,1,2,1,0,0,0,0,0
AILS2_Eta_Cycle_continue_3600_0.5,0,0,1,3,2,0,0,1,0,0,1,0,0,0
AILS2_Eta_Cycle_continue_3600_0.75,0,2,0,1,1,0,2,0,0,0,1,0,1,0
AILS2_Eta_Cycle_continue_3600_1,0,0,0,1,4,0,0,1,1,0,0,0,1,0
AILSII_continue_1,4,1,1,0,0,0,0,1,0,0,0,0,0,1
Mahdi_baseline,1,4,0,1,0,1,0,0,0,0,0,1,0,0

In [23]:
import os
import glob
import pandas as pd
from collections import deque

def get_max_time_from_csv(file_path):
    """
    读取CSV文件的最后一行以提取最大时间。
    如果文件为空，返回 0。
    """
    # 1. 检查文件是否为空
    if os.path.getsize(file_path) == 0:
        return 0.0

    try:
        # 2. 打开文件并只读取最后一行 (使用 deque 只保留最后1行)
        with open(file_path, 'r', encoding='utf-8') as f:
            # deque(f, 1) 会高效地只抓取最后一行
            last_line_gen = deque(f, maxlen=1)
            
            if not last_line_gen: # 双重检查：如果文件有大小但内容为空（如只有换行符）
                return 0.0
            
            last_line = last_line_gen[0].strip()
            
            # 3. 解析数据: {time};{fitness}
            # 假设格式总是分号分隔，且第一列是时间
            if not last_line:
                return 0.0
                
            time_str = last_line.split(';')[0]
            return float(time_str)
            
    except Exception as e:
        print(f"处理文件 {os.path.basename(file_path)} 时出错: {e}")
        return 0.0 # 出错时默认返回0，或者根据需求改为 None

In [24]:


# ================= 配置路径 =================
# ===========================================

def analysis_max_times(target_path):
    method_name = os.path.basename(target_path)
    
    # 获取所有csv文件
    csv_files = glob.glob(os.path.join(target_path, "*.csv"))
    data_list = []
    
    print(f"正在处理 {len(csv_files)} 个文件...")
    
    for file in csv_files:
        max_time = get_max_time_from_csv(file)
        # 记录文件名（不含路径）和最大时间
        data_list.append({
            'filename': os.path.basename(file),
            'max_time': max_time
        })
    
    # 1. 生成 DataFrame
    df = pd.DataFrame(data_list)
    
    # 按文件名排序（可选，方便查看）
    df = df.sort_values(by='filename').reset_index(drop=True)
    
    print("--- 结果预览 (前5行) ---")
    print(df.head())
    
    print(f"\n--- 统计信息 - {method_name} ---")
    # 2. 做个统计 (均值、最大值、最小值、分位数等)
    stats = df['max_time'].describe()
    print(stats)
    
    zero_count = (df['max_time'] == 0).sum()
    print(f"\n完全无提升instance个数: {zero_count} / {len(df)}")

# 如果你想查看具体的时间分布情况
# print(df['max_time'].value_counts(bins=10))

In [25]:
target_path = f'{result_dir}/AILS_continue_Mahdi'  # 请修改为你的实际文件夹路径
analysis_max_times(target_path)

正在处理 0 个文件...

KeyError: 'filename'